# Generated by Django 4.1 on 2022-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del Técnico')),
                ('lastname', models.CharField(max_length=30, verbose_name='Apellido del Técnico')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nationality', models.CharField(max_length=35, verbose_name='Nacionalidad')),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['id'],
            },
        ),
    ]
