# Generated by Django 4.1 on 2022-09-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del Jugador')),
                ('lastname', models.CharField(max_length=30, verbose_name='Apellido del Jugador')),
                ('photoplayer', models.ImageField(upload_to='media')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('numTshirt', models.IntegerField(verbose_name='Número de Camiseta')),
                ('titled', models.CharField(max_length=35, verbose_name='¿Es Titulado?')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameposition')),
                ('teamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
                'ordering': ['id'],
            },
        ),
    ]
