# Generated by Django 4.1 on 2022-09-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['id'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Instructor'},
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='técnico',
        ),
    ]
